# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from crypto_signal_engine.contracts.v1 import ml_engine_pb2 as crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in crypto_signal_engine/contracts/v1/ml_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MlEngineServiceStub:
    """Private, versioned contract between the .NET orchestrator and the Python ML engine.

    The engine is an advisor. It answers two questions — "what is the signal for this market at these
    barriers" (GetSignal) and "given this bot's configuration and its open position, what now"
    (EvaluateBotDecision) — and nothing it returns is an instruction to trade. Authorization,
    position sizing, order submission and all durable state belong to the .NET service; see
    docs/ARCHITECTURE.md and docs/LIVE_TRADING_SAFETY.md.

    RETIRED, DO NOT REINTRODUCE: `enum Signal { SIGNAL_SELL, SIGNAL_HOLD, SIGNAL_BUY }` and
    `message SignalProbabilities`, along with the `PredictSignal` RPC that carried them. In that
    contract SELL meant "exit to cash", not "open a short". Reusing those names for directional
    trading would silently invert the meaning of a stored decision, so they are gone rather than
    redefined. Directional intent is `TradeDirection`.

    PRICES AND PERCENTAGES CROSS THIS BOUNDARY AS DECIMAL STRINGS, never as `double`. The .NET side
    holds money as `decimal` and the audit chain requires that the price the engine computed is the
    same price the database records, byte for byte. Only dimensionless quantities — probabilities,
    ratios, ATR multiples, timings — are floating point.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/crypto_signal.ml.v1.MlEngineService/GetCapabilities',
                request_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/crypto_signal.ml.v1.MlEngineService/GetModelInfo',
                request_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoResponse.FromString,
                _registered_method=True)
        self.GetSignal = channel.unary_unary(
                '/crypto_signal.ml.v1.MlEngineService/GetSignal',
                request_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetSignalRequest.SerializeToString,
                response_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetSignalResponse.FromString,
                _registered_method=True)
        self.EvaluateBotDecision = channel.unary_unary(
                '/crypto_signal.ml.v1.MlEngineService/EvaluateBotDecision',
                request_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.EvaluateBotDecisionRequest.SerializeToString,
                response_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.EvaluateBotDecisionResponse.FromString,
                _registered_method=True)


class MlEngineServiceServicer:
    """Private, versioned contract between the .NET orchestrator and the Python ML engine.

    The engine is an advisor. It answers two questions — "what is the signal for this market at these
    barriers" (GetSignal) and "given this bot's configuration and its open position, what now"
    (EvaluateBotDecision) — and nothing it returns is an instruction to trade. Authorization,
    position sizing, order submission and all durable state belong to the .NET service; see
    docs/ARCHITECTURE.md and docs/LIVE_TRADING_SAFETY.md.

    RETIRED, DO NOT REINTRODUCE: `enum Signal { SIGNAL_SELL, SIGNAL_HOLD, SIGNAL_BUY }` and
    `message SignalProbabilities`, along with the `PredictSignal` RPC that carried them. In that
    contract SELL meant "exit to cash", not "open a short". Reusing those names for directional
    trading would silently invert the meaning of a stored decision, so they are gone rather than
    redefined. Directional intent is `TradeDirection`.

    PRICES AND PERCENTAGES CROSS THIS BOUNDARY AS DECIMAL STRINGS, never as `double`. The .NET side
    holds money as `decimal` and the audit chain requires that the price the engine computed is the
    same price the database records, byte for byte. Only dimensionless quantities — probabilities,
    ratios, ATR multiples, timings — are floating point.
    """

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignal(self, request, context):
        """One-off signal for a requested market at requested barriers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateBotDecision(self, request, context):
        """Stateless bot advice. Everything the engine is allowed to know arrives in the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MlEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoRequest.FromString,
                    response_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoResponse.SerializeToString,
            ),
            'GetSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignal,
                    request_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetSignalRequest.FromString,
                    response_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetSignalResponse.SerializeToString,
            ),
            'EvaluateBotDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateBotDecision,
                    request_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.EvaluateBotDecisionRequest.FromString,
                    response_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.EvaluateBotDecisionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crypto_signal.ml.v1.MlEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crypto_signal.ml.v1.MlEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MlEngineService:
    """Private, versioned contract between the .NET orchestrator and the Python ML engine.

    The engine is an advisor. It answers two questions — "what is the signal for this market at these
    barriers" (GetSignal) and "given this bot's configuration and its open position, what now"
    (EvaluateBotDecision) — and nothing it returns is an instruction to trade. Authorization,
    position sizing, order submission and all durable state belong to the .NET service; see
    docs/ARCHITECTURE.md and docs/LIVE_TRADING_SAFETY.md.

    RETIRED, DO NOT REINTRODUCE: `enum Signal { SIGNAL_SELL, SIGNAL_HOLD, SIGNAL_BUY }` and
    `message SignalProbabilities`, along with the `PredictSignal` RPC that carried them. In that
    contract SELL meant "exit to cash", not "open a short". Reusing those names for directional
    trading would silently invert the meaning of a stored decision, so they are gone rather than
    redefined. Directional intent is `TradeDirection`.

    PRICES AND PERCENTAGES CROSS THIS BOUNDARY AS DECIMAL STRINGS, never as `double`. The .NET side
    holds money as `decimal` and the audit chain requires that the price the engine computed is the
    same price the database records, byte for byte. Only dimensionless quantities — probabilities,
    ratios, ATR multiples, timings — are floating point.
    """

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crypto_signal.ml.v1.MlEngineService/GetCapabilities',
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesRequest.SerializeToString,
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crypto_signal.ml.v1.MlEngineService/GetModelInfo',
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoRequest.SerializeToString,
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crypto_signal.ml.v1.MlEngineService/GetSignal',
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetSignalRequest.SerializeToString,
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateBotDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crypto_signal.ml.v1.MlEngineService/EvaluateBotDecision',
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.EvaluateBotDecisionRequest.SerializeToString,
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.EvaluateBotDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
