# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from crypto_signal_engine.contracts.v1 import ml_engine_pb2 as crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in crypto_signal_engine/contracts/v1/ml_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MlEngineServiceStub:
    """Private, versioned contract between the .NET orchestrator and Python ML engine.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/crypto_signal.ml.v1.MlEngineService/GetCapabilities',
                request_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/crypto_signal.ml.v1.MlEngineService/GetModelInfo',
                request_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoResponse.FromString,
                _registered_method=True)
        self.PredictSignal = channel.unary_unary(
                '/crypto_signal.ml.v1.MlEngineService/PredictSignal',
                request_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.PredictSignalRequest.SerializeToString,
                response_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.PredictSignalResponse.FromString,
                _registered_method=True)


class MlEngineServiceServicer:
    """Private, versioned contract between the .NET orchestrator and Python ML engine.
    """

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MlEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoRequest.FromString,
                    response_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoResponse.SerializeToString,
            ),
            'PredictSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictSignal,
                    request_deserializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.PredictSignalRequest.FromString,
                    response_serializer=crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.PredictSignalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crypto_signal.ml.v1.MlEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crypto_signal.ml.v1.MlEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MlEngineService:
    """Private, versioned contract between the .NET orchestrator and Python ML engine.
    """

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crypto_signal.ml.v1.MlEngineService/GetCapabilities',
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesRequest.SerializeToString,
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crypto_signal.ml.v1.MlEngineService/GetModelInfo',
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoRequest.SerializeToString,
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.GetModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crypto_signal.ml.v1.MlEngineService/PredictSignal',
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.PredictSignalRequest.SerializeToString,
            crypto__signal__engine_dot_contracts_dot_v1_dot_ml__engine__pb2.PredictSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
