// <auto-generated />
using System;
using CryptoSignal.Api.Adapter.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoSignal.Api.Migrations
{
    [DbContext(typeof(CryptoSignalDbContext))]
    [Migration("20260824152551_Trading")]
    partial class Trading
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.BotAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorUserName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("BotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BotPositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CandleOpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExchangeOrderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("KillSwitchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperatingMode")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrderFillId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderIntentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RiskDecisionId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StrategyDecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BotId", "OccurredAt")
                        .HasDatabaseName("IX_BotAuditEvents_BotId_OccurredAt");

                    b.HasIndex("CorrelationId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_BotAuditEvents_CorrelationId_Sequence")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("IX_BotAuditEvents_EventType_OccurredAt");

                    b.ToTable("BotAuditEvents", (string)null);
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.BotPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageEntryPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("AverageExitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("BarsHeld")
                        .HasColumnType("integer");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CloseReason")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClosedByOrderIntentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<decimal>("EntryNotional")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("FeesPaid")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("LastMarkPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTime?>("LastMarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxAdverseExcursion")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OpenedByOrderIntentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OpenedFromCandleOpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperatingMode")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("RealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopLossPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("TakeProfitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("UnrealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.Property<int>("Venue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BotId", "OpenedAt")
                        .HasDatabaseName("IX_BotPositions_BotId_OpenedAt");

                    b.HasIndex("BotId", "OperatingMode")
                        .IsUnique()
                        .HasDatabaseName("UX_BotPositions_BotId_OperatingMode_Open")
                        .HasFilter("\"Status\" = 1 AND \"IsDeleted\" = false");

                    b.ToTable("BotPositions", null, t =>
                        {
                            t.HasCheckConstraint("CK_BotPositions_Quantity_Positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.BotRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DecisionCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastTickAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OperatingMode")
                        .HasColumnType("integer");

                    b.Property<long>("OrderCount")
                        .HasColumnType("bigint");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TickCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BotId")
                        .IsUnique()
                        .HasDatabaseName("UX_BotRuns_BotId_Open")
                        .HasFilter("\"EndedAt\" IS NULL AND \"IsDeleted\" = false");

                    b.HasIndex("BotId", "StartedAt")
                        .HasDatabaseName("IX_BotRuns_BotId_StartedAt");

                    b.ToTable("BotRuns", (string)null);
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.ExchangeOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AverageFillPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FilledQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastReconciledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperatingMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrderIntentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.Property<int>("Venue")
                        .HasColumnType("integer");

                    b.Property<string>("VenueOrderId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("VenueUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .HasDatabaseName("IX_ExchangeOrders_ClientOrderId");

                    b.HasIndex("OrderIntentId");

                    b.HasIndex("Venue", "VenueOrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExchangeOrders_Venue_VenueOrderId")
                        .HasFilter("\"VenueOrderId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.ToTable("ExchangeOrders", (string)null);
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.KillSwitch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DisengagedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DisengagedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisengagedByUserName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EngagedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EngagedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EngagedByUserName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEngaged")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScopeBotId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ScopeOperatingMode")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeSymbol")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("ScopeVenue")
                        .HasColumnType("integer");

                    b.Property<string>("TriggerDetail")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "ScopeOperatingMode", "ScopeVenue", "ScopeBotId", "ScopeSymbol")
                        .IsUnique()
                        .HasDatabaseName("UX_KillSwitches_Scope_Engaged")
                        .HasFilter("\"IsEngaged\" = true AND \"IsDeleted\" = false");

                    b.ToTable("KillSwitches", null, t =>
                        {
                            t.HasCheckConstraint("CK_KillSwitches_ScopeTargetMatches", "(\n    (\"Scope\" = 1 AND \"ScopeOperatingMode\" IS NULL AND \"ScopeVenue\" IS NULL AND \"ScopeBotId\" IS NULL AND \"ScopeSymbol\" IS NULL)\n OR (\"Scope\" = 2 AND \"ScopeOperatingMode\" IS NOT NULL AND \"ScopeVenue\" IS NULL AND \"ScopeBotId\" IS NULL AND \"ScopeSymbol\" IS NULL)\n OR (\"Scope\" = 3 AND \"ScopeVenue\" IS NOT NULL AND \"ScopeOperatingMode\" IS NULL AND \"ScopeBotId\" IS NULL AND \"ScopeSymbol\" IS NULL)\n OR (\"Scope\" = 4 AND \"ScopeBotId\" IS NOT NULL AND \"ScopeOperatingMode\" IS NULL AND \"ScopeVenue\" IS NULL AND \"ScopeSymbol\" IS NULL)\n OR (\"Scope\" = 5 AND \"ScopeSymbol\" IS NOT NULL AND \"ScopeOperatingMode\" IS NULL AND \"ScopeVenue\" IS NULL AND \"ScopeBotId\" IS NULL)\n)");
                        });
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.MarketCandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Close")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Low")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Open")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("QuoteVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.Property<int>("Venue")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("Venue", "Symbol", "Interval", "OpenTime")
                        .IsUnique()
                        .HasDatabaseName("UX_MarketCandles_Venue_Symbol_Interval_OpenTime")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("MarketCandles", null, t =>
                        {
                            t.HasCheckConstraint("CK_MarketCandles_CloseTimeAfterOpenTime", "\"CloseTime\" > \"OpenTime\"");

                            t.HasCheckConstraint("CK_MarketCandles_HighNotBelowLow", "\"High\" >= \"Low\"");
                        });
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.OrderFill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExchangeOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fee")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("FeeAsset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsMaker")
                        .HasColumnType("boolean");

                    b.Property<int>("OperatingMode")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.Property<int>("Venue")
                        .HasColumnType("integer");

                    b.Property<string>("VenueTradeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeOrderId")
                        .HasDatabaseName("IX_OrderFills_ExchangeOrderId");

                    b.HasIndex("Venue", "VenueTradeId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderFills_Venue_VenueTradeId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("OrderFills", (string)null);
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.OrderIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<decimal>("EstimatedNotional")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("LimitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("OperatingMode")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("ReferencePrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("StopLossPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<Guid>("StrategyDecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("TakeProfitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int?>("TimeInForce")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderIntents_ClientOrderId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("StrategyDecisionId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderIntents_StrategyDecisionId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("BotId", "Status")
                        .HasDatabaseName("IX_OrderIntents_BotId_Status");

                    b.ToTable("OrderIntents", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderIntents_Quantity_Positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.RiskDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Allowed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailedChecksCsv")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OrderIntentId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderIntentId")
                        .IsUnique()
                        .HasDatabaseName("UX_RiskDecisions_OrderIntentId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("RiskDecisions", (string)null);
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.StrategyDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Atr")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<bool>("BarrierExtrapolated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BotRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CandleOpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CandleWindowDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("EngineRequestId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("EntryPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<double>("ExpectedValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<double>("LongConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ModelTrainedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OperatingMode")
                        .HasColumnType("integer");

                    b.Property<double>("ProbabilityStopLossFirst")
                        .HasColumnType("double precision");

                    b.Property<double>("ProbabilityTakeProfitFirst")
                        .HasColumnType("double precision");

                    b.Property<double>("ProbabilityTimeout")
                        .HasColumnType("double precision");

                    b.Property<double>("ProcessingMilliseconds")
                        .HasColumnType("double precision");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("RiskRewardRatio")
                        .HasColumnType("double precision");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<double>("ShortConfidence")
                        .HasColumnType("double precision");

                    b.Property<double?>("StopLossAtr")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("StopLossPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<double?>("TakeProfitAtr")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("TakeProfitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UsedWildcardModel")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Warning")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("BotRunId");

                    b.HasIndex("BotId", "CandleOpenTime")
                        .IsUnique()
                        .HasDatabaseName("UX_StrategyDecisions_BotId_CandleOpenTime")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("StrategyDecisions", (string)null);
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.TradingBot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowShort")
                        .HasColumnType("boolean");

                    b.Property<int>("CadenceSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExpectedModelVersion")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("FaultedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastEvaluatedCandleOpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastTickAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxConcurrentPositions")
                        .HasColumnType("integer");

                    b.Property<int>("MaxConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxDailyLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("MaxDrawdown")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("MaxHoldingPeriods")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxOrderNotional")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("MaxOrdersPerDay")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxPositionNotional")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("MaxSlippageBps")
                        .HasColumnType("integer");

                    b.Property<double>("MinimumConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OperatingMode")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuoteNotionalPerTrade")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("StopLossPercent")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TakeProfitPercent")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.Property<int>("Venue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_TradingBots_Name_Active")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TradingBots_Status");

                    b.HasIndex("OperatingMode", "Symbol", "Interval")
                        .HasDatabaseName("IX_TradingBots_Mode_Symbol_Interval");

                    b.ToTable("TradingBots", null, t =>
                        {
                            t.HasCheckConstraint("CK_TradingBots_CadenceSeconds_Positive", "\"CadenceSeconds\" > 0");

                            t.HasCheckConstraint("CK_TradingBots_QuoteNotionalPerTrade_Positive", "\"QuoteNotionalPerTrade\" > 0");

                            t.HasCheckConstraint("CK_TradingBots_StopLossPercent_Positive", "\"StopLossPercent\" > 0");

                            t.HasCheckConstraint("CK_TradingBots_TakeProfitPercent_Positive", "\"TakeProfitPercent\" > 0");
                        });
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.BaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastPasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PersonelCode")
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("RequirePasswordChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PersonelCode")
                        .HasDatabaseName("IX_Users_PersonelCode");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_UserName_Active")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LoginType")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_LoginHistory_CreatedAt");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_LoginHistory_Status_CreatedAt");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_LoginHistory_User_CreatedAt");

                    b.ToTable("LoginHistories", null, t =>
                        {
                            t.HasCheckConstraint("CK_LoginHistory_Status_Range", "\"Status\" >= 0 AND \"Status\" <= 5");
                        });
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("character varying(150)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Permissions_Name_Active")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Permissions_Title");

                    b.ToTable("Permissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Permissions_Name_NotEmpty", "TRIM(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_Name_Active")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Roles_Title");

                    b.ToTable("Roles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Roles_Name_NotEmpty", "TRIM(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermissions_PermissionId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_RolePermissions_RoleId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserCreatedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCreatedName")
                        .HasColumnType("text");

                    b.Property<string>("UserLastUpdateName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserLastUpdatedId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRoles_UserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Auth.User", b =>
                {
                    b.HasBaseType("CryptoSignal.Auth.Domain.Models.BaseUser");

                    b.Property<string>("Mobile")
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("UserType")
                        .HasColumnType("integer");

                    b.HasIndex("UserType")
                        .HasDatabaseName("IX_Users_UserType");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.BotPosition", b =>
                {
                    b.HasOne("CryptoSignal.Api.Domain.Models.Trading.TradingBot", null)
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.BotRun", b =>
                {
                    b.HasOne("CryptoSignal.Api.Domain.Models.Trading.TradingBot", null)
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.ExchangeOrder", b =>
                {
                    b.HasOne("CryptoSignal.Api.Domain.Models.Trading.OrderIntent", null)
                        .WithMany()
                        .HasForeignKey("OrderIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.OrderFill", b =>
                {
                    b.HasOne("CryptoSignal.Api.Domain.Models.Trading.ExchangeOrder", null)
                        .WithMany()
                        .HasForeignKey("ExchangeOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.OrderIntent", b =>
                {
                    b.HasOne("CryptoSignal.Api.Domain.Models.Trading.TradingBot", null)
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoSignal.Api.Domain.Models.Trading.StrategyDecision", null)
                        .WithMany()
                        .HasForeignKey("StrategyDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.RiskDecision", b =>
                {
                    b.HasOne("CryptoSignal.Api.Domain.Models.Trading.OrderIntent", null)
                        .WithMany()
                        .HasForeignKey("OrderIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoSignal.Api.Domain.Models.Trading.StrategyDecision", b =>
                {
                    b.HasOne("CryptoSignal.Api.Domain.Models.Trading.TradingBot", null)
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoSignal.Api.Domain.Models.Trading.BotRun", null)
                        .WithMany()
                        .HasForeignKey("BotRunId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.BaseUser", b =>
                {
                    b.HasOne("CryptoSignal.Auth.Domain.Models.BaseUser", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.LoginHistory", b =>
                {
                    b.HasOne("CryptoSignal.Auth.Domain.Models.BaseUser", "BaseUser")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseUser");
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.RolePermission", b =>
                {
                    b.HasOne("CryptoSignal.Auth.Domain.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoSignal.Auth.Domain.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.UserRole", b =>
                {
                    b.HasOne("CryptoSignal.Auth.Domain.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoSignal.Auth.Domain.Models.BaseUser", "BaseUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.BaseUser", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("LoginHistories");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CryptoSignal.Auth.Domain.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
